# AML Final Project
## West Group 7

### Downloading Data

In [1]:
import pandas as pd
from datasets import load_dataset

In [2]:
# Load banking dataset from Hugging Face
bank_df = load_dataset('mteb/banking77') # Hugging Face location

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

You can ignore this warning: 

- Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
# preview data
bank_df

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 9993
    })
    test: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 3076
    })
})

This dataset comes pre-split into a train and test set. We can store these individually. The split is approximately 76% - 24%.

In [4]:
# store train and test sets
train_df = bank_df['train'].to_pandas()
test_df  = bank_df['test'].to_pandas()

In [5]:
train_df.head()

                                                text  label    label_text
0                     I am still waiting on my card?     11  card_arrival
1  What can I do if my card still hasn't arrived ...     11  card_arrival
2  I have been waiting over a week. Is the card s...     11  card_arrival
3  Can I track my card while it is in the process...     11  card_arrival
4  How do I know if I will get my card, or if it ...     11  card_arrival

In [6]:
train_df.shape

(9993, 3)

In [7]:
train_label_counts_df = train_df.label_text.value_counts().reset_index()
# train_label_counts_df = pd.DataFrame(s, columns = ['count'])

train_label_counts_df

                                          label_text  count
0                           card_payment_fee_charged    187
1                direct_debit_payment_not_recognised    182
2   balance_not_updated_after_cheque_or_cash_deposit    181
3                      wrong_amount_of_cash_received    180
4                             cash_withdrawal_charge    177
..                                               ...    ...
72                               lost_or_stolen_card     82
73                                    card_swallowed     61
74                                   card_acceptance     59
75                          virtual_card_not_working     41
76                           contactless_not_working     35

[77 rows x 2 columns]

# Other Thoughts

These don't need to be our final splits. The purpose here is only to download the data from the same source in the same way.